<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit467103e792ca76e1258e38ddcae47b38
{
    public static $prefixLengthsPsr4 = array (
        'E' => 
        array (
            'Elliptic\\' => 8,
        ),
        'B' => 
        array (
            'BN\\' => 8,
            'BI\\' => 8,
        ),
    );
    
    
    public static $prefixDirsPsr4 = array (
        'Elliptic\\' => 
        array (
            0 => __DIR__ . '/..',
        ),
        'BN\\' => 
        array (
            0 => __DIR__ . '/../BN',
        ),
        'BI\\' => 
        array (
            0 => __DIR__ . '/../BI',
        ),
    );
    

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
    	
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit467103e792ca76e1258e38ddcae47b38::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit467103e792ca76e1258e38ddcae47b38::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit467103e792ca76e1258e38ddcae47b38::$classMap;

        }, null, ClassLoader::class);
        
    }
}
